---
- name: try to stop old garbd service
  service: name="{{ garbd_service }}" state=stopped enabled=false pattern=/usr/bin/garbd
  when: ansible_os_family == 'Debian'
  failed_when: False

- name: try to stop old garbd service
  service: name="{{ garbd_service }}" state=stopped enabled=false
  when: ansible_os_family == 'RedHat'
  failed_when: False

- name: make garbd log
  copy: dest=/var/log/garbd.log owner=nobody content='' force=no

- name: galera data dir
  file:
    path: /var/lib/galera
    owner: nobody
    state: directory

# the arbiter node only needs the garbd daemon
- name: install percona garbd package
  package: pkg=percona-xtradb-cluster-garbd-3.x state=installed
  when: ansible_os_family == 'Debian'
  register: result
  until: result|succeeded
  retries: 5

- name: install percona garbd package
  package: pkg=Percona-XtraDB-Cluster-garbd-3 state=installed
  when: ansible_os_family == 'RedHat'
  register: result
  until: result|succeeded
  retries: 5

- name: install garbd config
  template: src=etc/default/garbd dest=/etc/default/garbd mode=0644
  when: ansible_os_family == 'Debian'

- name: install garbd config
  template: src=etc/default/garbd dest=/etc/sysconfig/garb mode=0644
  when: ansible_os_family == 'RedHat'

- name: ensure garbd running
  service: name="{{ garbd_service }}" state=started enabled=yes pattern=/usr/bin/garbd
  when: ansible_os_family == 'Debian'

- name: ensure garbd running
  service: name="{{ garbd_service }}" state=started enabled=yes
  when: ansible_os_family == 'RedHat'
