---
dependencies:
  - role: apt-repos
    repos:
      - repo: 'deb {{ apt_repos.chef.repo }} trusty main'
        key_url: '{{ apt_repos.chef.key_url }}'
    when: ansible_os_family == 'Debian'
  - role: repos
    repo: chef
    when: ansible_os_family == 'RedHat'
