---
- name: set os fact for rhel operating system
  set_fact:
    os: rhel
  when: ansible_distribution in ['CentOS', 'RedHat']

- name: set os fact for rhel operating system
  set_fact:
    os: ubuntu
  when: ansible_distribution in ['Ubuntu']

- name: make sure os is defined
  fail: msg="We don't support {{ ansible_distribution }} yet. OS should be CentOS, RedHat or Ubuntu."
  when: os is undefined

- name: set ssh_service fact for ubuntu
  set_fact:
    ssh_service: ssh
  when: ansible_os_family == 'Debian'

- name: set ssh_service fact for rhel
  set_fact:
    ssh_service: sshd
  when: ansible_os_family == 'RedHat'

- name: set ca_bundle fact for ubuntu
  set_fact:
    ca_bundle: /etc/ssl/certs/ca-certificates.crt
  when: ansible_os_family == 'Debian'

- name: set ca_bundle fact for rhel
  set_fact:
    ca_bundle: /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
  when: ansible_os_family == 'RedHat'




- block:
  - name: check ceph installed
    command: ceph --version
    register: result_ceph_installed
    failed_when: false
    delegate_to: "{{ groups['ceph_monitors'][0] }}"

  - name: Check whether Cinder endpoint exists
    shell: . /root/stackrc; openstack endpoint list | grep cinder
    failed_when: false
    register: result_cinder_endpoint
    delegate_to: "{{ groups['controller'][0] }}"

  - include: ceph.yml
    when:
      - result_ceph_installed.rc == 0
      - result_cinder_endpoint.rc == 0

  when: ceph.enabled | default('False') | bool
  tags: ['precheck', 'precheck_ceph']
  run_once: true
